### PR TITLE
SDL window init: test availability of AA/subsampling before requiring it

### PR DESCRIPTION
**Pull request by jcaesar**
No answer in #137 but whatever. It does fix the issue on my machine.

### CODE REVIEW

**Comment by lluchs** [comment]
Ah, I wanted to try this, but then had unrelated OpenGL issues on my laptop. I'll have another look...

**Comment by jcaesar** [comment]
Ty. I don't have a windows available for testing, either… :/

**Comment by lluchs** [comment]
The patch works on my system. Maybe it should also change invalid configuration values. Currently, it will show 4x MSAA in the options even when it's in fact disabled.

**Comment by jcaesar** [comment]
I made it write the actual multisampling value back to the config.

Good thing you brought it up. Turns out that calling `glGetIntegerv(GL_MAX_SAMPLES, &max_samples);` at that point (probably before creating the first window, but I'm not sure what the reason is) will return 0, even if AA is available. So the original patch would have broken AA for everything.
I added a workaround.

**Pull request merged**
